figure('Name','A Circuit','Numbertitle', 'off',... 
'Color', [.3 .3 .4]); 
h = uimenu('Label','User_Menu'); 
uimenu(h,'Label','New Figure','Callback','figure'); 
h1=uimenu(h,'Label','Save','Callback','save'); 
uimenu(h,'Label','Close','Callback','close',... 
'Separator','on','Accelerator','Q'); 
uimenu(h1,'Label','Save R'); 
uimenu(h1,'Label','Save L'); 
uimenu(h1,'Label','Save All'); 
%remember defining some pushbuttons 
uicontrol('Style','pushbutton','Units','normalized',... 
'Position',[0.175 0.03 0.1 0.05],... 
'String','Func1','Callback','','Visible','on'); 
uicontrol('Style','pushbutton','Units','normalized',... 
'Position',[0.475 0.03 0.1 0.05],... 
'String','Func2','Callback','','Visible','on'); 
uicontrol('Style','pushbutton','Units','normalized',... 
'Position',[0.775 0.03 0.1 0.05],... 
'String','CLOSE','Callback','close;');