%Create a gui figure with a menu and graphics elements 
clear all; 
close all; 
%creating the figure 
Fig=figure('Name','Interface',... 
'Position',[400 400 400 300],... 
'NumberTitle','off'); 
%creating the menu item with figure as parent 
% you must have the jpg file in the current folder 
meniu=uimenu(Fig,'Text','USER_Menu'); 
% creating the submenu items having  
% meniu item as parent 
item1=uimenu(meniu,"Text",'DOCX Front Page', ... 
'Accelerator','A',... 
'Callback', 'open("FrontPage.docx")' ); 
item2=uimenu(meniu,"Text",'HTML Front Page', ... 
'Accelerator','B',... 
'Callback', 'open("FrontPage.htm")' ); 
item3=uimenu(meniu,"Text",'LPF Circuit', ...  
'Accelerator','C',... 
'Callback', 'imshow("LPF.jpg")'); 
item4=uimenu(meniu,"Text",'CLOSE', ... 
'Separator','on',... 
'Accelerator','X',... 
'Callback','close'); 
% creating the buttons in the figure window 
uicontrol('Style','pushbutton',... 
'Units','normalized',... 
'Position',[0.025 0.02 0.3 0.1],... 
'String','Front Page .docx',... 
'Callback','front_pagedocx'); 
uicontrol('Style','pushbutton',... 
'Units','normalized',... 
'Position',[0.35 0.02 0.3 0.1],... 
'String','Front Page .html',... 
'Callback','front_pagehtm'); 
uicontrol('Style','pushbutton',... 
'Units','normalized',... 
'Position',[0.67 0.02 0.3 0.1],... 
'String','LPF',... 
'Callback','imshow("LPF.jpg")') 