function openInterface(~)

close all;

% default parameters 
P.type = "square";
P.N    = 10;
P.showOriginal = 1;

mainFig = figure('Name','Fourier Series Visualizer', ...
    'NumberTitle','off', ...
    'Color','#eef4ff', ...
    'Units','normalized', ...
    'Position',[0.25 0.18 0.60 0.70]);

% store params
setappdata(mainFig,'P',P);

% sidebar background
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0 0 0.28 1], ...
    'BackgroundColor','#dce9ff', ...
    'ForegroundColor','#1f1f1f', ...
    'String','');

% axes time
axTime = axes('Parent',mainFig, ...
    'Units','normalized', ...
    'Position',[0.33 0.55 0.64 0.40]);
grid on;

% axes spectrum
axSpec = axes('Parent',mainFig, ...
    'Units','normalized', ...
    'Position',[0.33 0.10 0.64 0.38]);
grid on;

% store handles
H.axTime = axTime;
H.axSpec = axSpec;
setappdata(mainFig,'H',H);

% controls
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.04 0.86 0.20 0.05], ...
    'BackgroundColor','#dce9ff', ...
    'ForegroundColor','#1f1f1f', ...
    'HorizontalAlignment','left', ...
    'String','Waveform');

uicontrol('Style','popupmenu', ...
    'Units','normalized', ...
    'Position',[0.04 0.82 0.20 0.05], ...
    'ForegroundColor','#1f1f1f', ...
    'BackgroundColor','white', ...
    'String',{'square','sawtooth','triangle'}, ...
    'Value',1, ...
    'Callback','cbType');

uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.04 0.74 0.20 0.05], ...
    'ForegroundColor','#1f1f1f', ...
    'BackgroundColor','#dce9ff', ...
    'HorizontalAlignment','left', ...
    'String','N (harmonics)');

uicontrol('Style','slider', ...
    'Units','normalized', ...
    'Position',[0.04 0.70 0.20 0.04], ...
    'Min',1,'Max',50,'Value',10, ...
    'SliderStep',[1/49 10/49], ...
    'Callback','cbN');

uicontrol('Style','checkbox', ...
    'Units','normalized', ...
    'Position',[0.04 0.62 0.22 0.06], ...
    'BackgroundColor','#dce9ff', ...
    'ForegroundColor','#1f1f1f', ...
    'Value',1, ...
    'String','Show original', ...
    'Callback','cbShow');

uicontrol('Style','pushbutton', ...
    'Units','normalized', ...
    'BackgroundColor','#b7cff5', ...
    'ForegroundColor','#1f1f1f', ...
    'FontWeight','bold', ...
    'String','close', ...
    'Callback','close');

% initial plot
P = getappdata(mainFig,'P');
computeFourier(P, axTime, axSpec);

end
