 % main file - START
close all;

% initial settings (example default)
waveType = "square";

% new figure for the start interface
fig = figure('Name', 'Fourier Series Visualizer', ...
    'NumberTitle', 'off', ...
    'Color', '#e8f0ff', ...
    'Units', 'normalized', ...
    'Position', [0.30 0.22 0.40 0.60]);

% set the background
bgImage = imread('images/background.jpg');
axes('Units', 'normalized', ...
    'Position', [0 0 1 1]);
imshow(bgImage);
hold on;

% title
annotation('textbox',[0.12 0.72 0.76 0.2], ...
    'String','Fourier Series Visualizer', ...
    'HorizontalAlignment','center', ...
    'FontSize',26, ...
    'FontWeight','bold', ...
    'EdgeColor','none', ...
    'Color','#1f1f1f');

% subtitle
annotation('textbox', [0.12 0.64 0.76 0.1], ...
    'String', 'CAG Final Project 2025-2026', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', 12, ...
    'EdgeColor', 'none', ...
    'BackgroundColor', 'none', ...
    'Color', 'black');

% button to open the main interface
uicontrol('Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'FontSize', 14, ...
    'BackgroundColor', '#b7cff5', ...
    'ForegroundColor','#1f1f1f', ...
    'Position', [0.35 0.40 0.3 0.1], ...
    'String', 'start', ...
    'Callback', 'openInterface(fig)');

% button to display the documentation
uicontrol('Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[0.30 0.54 0.45 0.1], ...
    'String','documentation', ...
    'FontSize',14, ...
    'BackgroundColor','#b7cff5', ...
    'ForegroundColor','#1f1f1f', ...
    'Callback','open("documentation/Fourier_Series_Visualizer.docx")');

% close button
uicontrol('Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'FontWeight', 'bold', ...
    'FontSize', 12, ...
    'BackgroundColor', '#b7cff5', ...
    'ForegroundColor','#1f1f1f', ...
    'Position', [0.82 0.08 0.12 0.07], ...
    'String', 'close', ...
    'Callback', 'close');
