% Build an interface that does the following: - 
%represents graphically functions sin, cos and sin+cos in 3 different windows  - - - - - 
%allows modifying the amplitudes for sin and cos, frequency and number of 
%displayed periods  
%the variable for sine amplitude is A, for cos amplitude is B, for frequency is f and 
%number of periods is N 
%The initial values are A=10; B=5; f=50 Hz; N=4 
%The gui contains a button for CLOSE and a button for RESET (resetting the 
%characteristics to their initial values) 
%The interface should also contain a menu for: displaying the front page in pdf, resetting 
%the characteristics to the initial values, displaying a jpg image and a closing function 

close all; 
A=10; % magnitude of signal 1 = sinus 
B=5;  % magnitude signal 2    = cosinus 
f=50; % defining the frequency in Hz 
N=4;  % number of displayed cycles 
%creating a new figure 
Fig=figure('Name','Laboratory 11',...  
'Units','normalized',... 
'NumberTitle','off',... 
'Position',[0.1 0.1 0.8 0.8],... 
'Color',[0.5 0.5 0.9]); 
% creates user menu item in main menu 
meniu=uimenu(Fig,'Text','User Menu'); 
% menu item that opens front page 
item1=uimenu(meniu,"Text",'PDF Front Page', ... 
'Accelerator','A',... 
'Callback', 'open("FrontPage.pdf")' ); 
% menu item that resets characteristics to initial values 
% therefore the interfata function call with 
% initial numeric values 
item2=uimenu(meniu,"Text",'Reset to initial', ... 
'Accelerator','B',... 
'Callback', 'interfata(10,5,50,4);' ); 
% displays a picture using a function 
item3=uimenu(meniu,"Text",'Display Picture', ...  
'Accelerator','C',... 
'Callback','display_pic'); 
% menu item close button 
item4=uimenu(meniu,"Text",'CLOSE', ... 
'Separator','on',... 
'Accelerator','X',... 
'Callback','close'); 
% pushbuton CLOSE 
uicontrol('Style','pushbutton',...  
'Units','normalized',... 
'Position',[0.9 0.9 0.08 .05],... 
'String','CLOSE',... 
'Backgroundcolor','#FAF0E6',... 
'ForegroundColor','#800080',... 
'FontName','Arial',... 
'FontWeight','bold',... 
'FontSize',12,... 
'Callback','close'); 
% static text indicating default values 
uicontrol('Style','text',...  
'Units','normalized',... 
'Position',[0.5 0.83 0.37 .08],... 
'Backgroundcolor',[0.5 0.5 0.9],... 
'FontName','Arial',... 
'FontWeight','bold',... 
'FontSize',18,... 
'String','Default values: A=10, B=5, f=50, N=4'); 
interfata(A,B,f,N)