%Design a gui for an inverting and noninverting amplifier. Consider a main 
%window having the: 
% Title Amplifier 
% 3 buttons in the center for: 
%o Documentation 
%o Noninverting amplifier 
%o Inverting amplifiers 
%o And a Close button on the right down part

close all; 
% initial settings for circuit variables 
A=5; 
R1=20e3; R2=10e3; 
Vps1=12; Vps2=-12; 
f=50e2;  
N=5; 
d=1; 
 
% creating a new figure for the main interface 
figure ('Name','Amplifiers',... 
        'Numbertitle', 'off',... 
        'Color','#CCCCFF',... 
        'Units','normalized',... 
        'Position',[0.3 0.3 0.3 0.5]); 
    
 uicontrol('Style','text',... 
           'Units','normalized',... 
           'Fontsize', 24,... 
           'FontWeight','bold',... 
           'BackgroundColor','#CCCCFF',... 
           'Position',[0.35 0.8 0.34 0.09],... 
           'String','AMPLIFIERS'); 
 
% button to display the documentation 
uicontrol('Style','pushbutton',... 
          'Units','normalized',... 
          'Fontsize', 14,... 
          'BackgroundColor','#D6CADD',... 
          'Position',[0.3 0.6 0.45 0.1],... 
          'String','Documentation',... 
          'Callback','documentation'); 
 
% close button 
uicontrol('Style','pushbutton',...  
          'Units','normalized',... 
          'FontWeight','bold',... 
          'Fontsize', 12,... 
          'BackgroundColor','#D6CADD',... 
          'Position',[0.85 0.03 0.1 0.06],... 
          'string','Close',... 
          'Callback','close'); 
 
% creates the figure for the noninverting amplifier  
% the variable avin is set to 0 
% and the "createfig" function is called 
uicontrol('Style','pushbutton',... 
          'Units','normalized',... 
          'Fontsize', 14,... 
          'BackgroundColor','#D6CADD',... 
          'Position',[0.3 0.4 0.45 0.1],... 
          'String','NONINVERTING Amplifier',...           
'Callback','avin=0;createfig(avin,d,A,R1,R2,Vps1,Vps2,f,N)'); 
 
           
% creates the figure for the inverting amplifier  
% the variable avin is set to 1 and "createfig" function  
% is called 
uicontrol('Style','pushbutton',... 
'Units','normalized',... 
'Fontsize', 14,... 
'BackgroundColor','#D6CADD',... 
'Position',[0.3 0.2 0.45 0.1],... 
'String','INVERTING Amplifier',...           
'Callback','avin=1;createfig(avin,d,A,R1,R2,Vps1,Vps2,f,N)');