function interfata(A,B,f,N) 
T=1/f; % defining the cycle of the signal 
t=0:T/100:N*T; % representation range in time 
x1=A*sin(2*pi*f*t); % first function 
x2=B*cos(5*2*pi*f*t); % second function 
x3=x1+x2; % sum of the two functions sine and cosine 
% text button for variable A = sine Amplitude 
uicontrol('Style','text',...  
'Units','normalized',... 
'Position',[0.9 0.83 0.08 .05],... 
'Backgroundcolor',[0.5 0.5 0.9],... 
'String','A'); 
% edit button for A numeric value 
uicontrol('Style','edit',...  
'Units','normalized',... 
'Position',[0.9 0.80 0.08 .05],... 
'String',A,... 
'Backgroundcolor','#FAF0E6',... 
'Callback','A=str2num(get(gco,"String"));interfata(A,B,f,N);'); 
% text button for variable B = cosine Amplitude 
uicontrol('Style','text',...  
'Units','normalized',... 
'Position',[0.9 0.73 0.08 .05],... 
'backgroundcolor',[0.5 0.5 0.9],... 
'string','B'); 
% edit button for B numeric value 
uicontrol('Style','edit',...  
'Units','normalized',... 
'Position',[0.9 0.70 0.08 .05],... 
'Backgroundcolor','#FAF0E6',... 
'String',B,... 
'Callback','B=str2num(get(gco,"String"));interfata(A,B,f,N);'); 
% text button for f =frequency 
uicontrol('Style','text',...  
'Units','normalized',... 
'Position',[0.9 0.63 0.08 .05],... 
'Backgroundcolor',[0.5 0.5 0.9],... 
'String','f'); 
% edit button for f numeric value 
uicontrol('Style','edit',...  
'Units','normalized',... 
'Position',[0.9 0.60 0.08 .05],... 
'Backgroundcolor','#FAF0E6',... 
'String',f,... 
'Callback','f=str2num(get(gco,"String"));interfata(A,B,f,N);'); 
% text button for N = nr of cycles to be displayed 
uicontrol('Style','text',...  
'Units','normalized',... 
'Position',[0.9 0.53 0.08 .05],... 
'Backgroundcolor',[0.5 0.5 0.9],... 
'String','N'); 
% edit button for N numeric value 
uicontrol('Style','edit',...  
'Units','normalized',... 
'Position',[0.9 0.50 0.08 .05],... 
'Backgroundcolor','#FAF0E6',... 
'String',N,... 
'Callback','N=str2num(get(gco,"String"));interfata(A,B,f,N);'); 
% Pushbutton for Reset - returns the characteristics 
% with the initially displayed values 
uicontrol('Style','pushbutton',...  
'Units','normalized',... 
'Position',[0.85 0.2 0.13 .05],... 
'String','Reset to Initial Values',... 
'Backgroundcolor','#FAF0E6',... 
'ForegroundColor','#800080',... 
'FontName','Arial',... 
'FontWeight','bold',... 
'FontSize',12,... 
'Callback','interfata(10,5,50,4);'); %call with initial values 
% setting the plot windows 
subplot('position',[0.1 0.72 0.4 0.25]); 
plot(t,x1,'m', 'LineWidth',1.5); 
grid on; 
title('Sinus '); 
xlabel('time [s]'); 
ylabel('Amplitude A [V]'); 
subplot('position',[0.1 0.38 0.4 0.25]); 
plot(t,x2, 'm','LineWidth',1.5); 
grid on; 
title('Cosinus '); 
xlabel('time [s]'); 
ylabel('Amplitude B [V]'); 
subplot('position',[0.1 0.05 0.4 0.25]); 
plot(t,x3,'b', 'LineWidth',1.5); 
grid on; 
title('Sum of Sin+Cos '); 
xlabel('time [s]'); 
ylabel('Amplitude A+B [V]'); 
end