function myInterface(avin,d,A,R1,R2,Vps1,Vps2,f,N) 
% creates a container for the buttons 
% of the wave form types=SINUS OR TRIANGLE 
Tip_semnal=uibuttongroup('Visible','on',... 
                     'BackgroundColor','#D6CADD',... 
                         'ForegroundColor','black',...  
                         'Title','Waveform',... 
                         'FontSize',14,... 
                         'TitlePosition','centertop',...  
                         'Position',[ 0.3 0.6 0.16 0.37]); 
                      
% if the user pushes the button "Sinus" 
% d=1 and the input voltage is a sine wave  
% observe in callback                     
uicontrol('Style','pushbutton',... 
          'Units','normalized',... 
          'Position',[0.1 0.6 0.8 0.2],... 
          'Fontsize', 14,... 
          'String','SINUS',... 
          'backgroundcolor', [0.9 0.9 0.9],... 
          'Parent', Tip_semnal,... 
'Callback','d=1;myInterface(avin,d,A,R1,R2,Vps1,Vps2,f,N)'); 
 
% if the user pushes the button "Triangle"         
% d=2 and the input voltage is a triangular wave 
% observe in callback                     
uicontrol('Style','pushbutton',... 
          'Units','normalized',... 
          'Position',[0.1 0.2 0.8 0.2],... 
          'Fontsize', 14,... 
          'String','TRIANGLE',... 
          'backgroundcolor', [0.9 0.9 0.9],... 
          'Parent', Tip_semnal,... 
'Callback','d=2;myInterface(avin,d,A,R1,R2,Vps1,Vps2,f,N)'); 
           
% the button container group is created 
% with the circuit parameter names textbuttons 
% and edit buttons with circuit parameter values 
Parameters=uibuttongroup('Visible','on',... 
                        'BackgroundColor','#D6CADD',... 
                        'ForegroundColor','black',... 
                        'Title','Parameters',... 
                        'FontSize',14,... 
                        'TitlePosition','centertop',...                
                        'Position', [ 0.05 0.6 0.18 0.37]);  
 
% in the following code lines OBSERVE THE PAIRS 
% TEXT + EDIT BUTTONS FOR EACH MODIFIABLE VARIABLE 
 
% text button for R1                    
 uicontrol('Style','text',... 
          'Units','normalized',... 
          'Position', [0.1 0.76 0.27 0.1],... 
          'backgroundcolor', [0.9 0.9 0.9],... 
          'foregroundcolor','black',... 
          'fontweight', 'bold',... 
          'fontsize', 10,... 
          'string','R1',... 
          'Parent',Parameters);   
% edit for R1        
uicontrol('Style','edit',...     
          'Units','normalized',... 
          'Position',[0.5 0.76 0.27 0.1],... 
          'backgroundcolor',[0.9 0.9 0.9],... 
          'foregroundcolor','black',... 
          'fontweight','bold',... 
          'fontsize',10,... 
          'String',R1,... 
          'Parent',Parameters,... 
 'Callback',['R1=str2num(get(gco, "String")),' ... 
 'myInterface(avin,d,A,R1,R2,Vps1,Vps2,f,N)']); 
 
% text button for R2                     
uicontrol('Style','text',...     
          'Units','normalized',... 
          'Position',[0.1 0.65 0.27 0.1],... 
          'backgroundcolor',[0.9 0.9 0.9] ,... 
          'foregroundcolor','black',... 
          'fontweight','bold',... 
          'fontsize',10,... 
          'string','R2',... 
          'Parent',Parameters);      
% edit for R2       
uicontrol('Style','edit',... 
          'Units','normalized',... 
          'Position',[0.5 0.65 0.27 0.1],... 
          'backgroundcolor',[0.9 0.9 0.9],... 
          'foregroundcolor','black',... 
          'fontweight','bold',... 
          'fontsize',10,... 
          'String',R2,... 
          'Parent',Parameters,...  
'Callback',['R2=str2num(get(gco, "String")),' ... 
'myInterface(avin,d,A,R1,R2,Vps1,Vps2,f,N)']); 
 
% text button for +Vps 
uicontrol('Style','text',...  
          'Units','normalized',... 
          'Position',[0.1 0.54 0.27 0.1],... 
          'backgroundcolor',[0.9 0.9 0.9] ,... 
          'foregroundcolor','black',... 
          'fontweight','bold',... 
          'fontsize',10,... 
          'string','+Vps',... 
          'Parent',Parameters);  
% edit for +Vps       
uicontrol('Style','edit',...  
           'Units','normalized',... 
           'Position',[0.5 0.54 0.27 0.1],... 
           'backgroundcolor',[0.9 0.9 0.9],... 
           'foregroundcolor','black',... 
           'fontweight','bold',... 
           'fontsize',10,... 
           'String',Vps1,...   % Vps1 = +Vps 
           'Parent',Parameters,... 
'Callback',['Vps1=str2num(get(gco,"String")),' ... 
'myInterface(avin,d,A,R1,R2,Vps1,Vps2,f,N)']); 
 
% text button for -Vps        
uicontrol('Style','text',...  
          'Units','normalized',... 
          'Position',[0.1 0.43 0.27 0.1],... 
          'backgroundcolor',[0.9 0.9 0.9] ,... 
          'foregroundcolor','black',... 
          'fontweight','bold',... 
          'fontsize',10,... 
          'string','-Vps',... 
          'Parent',Parameters);  
 % edit for -Vps     
 uicontrol('Style','edit',...  
           'Units','normalized',... 
           'Position',[0.5 0.43 0.27 0.1],... 
           'backgroundcolor',[0.9 0.9 0.9],... 
           'foregroundcolor','black',... 
           'fontweight','bold',... 
           'fontsize',10,... 
           'String',Vps2,... 
           'Parent',Parameters,... 
'Callback',['Vps2=str2num(get(gco,"String")),' ... 
'myInterface(avin,d,A,R1,R2,Vps1,Vps2,f,N)']); 
 
% text button for f 
uicontrol('Style','text',...  
          'Units','normalized',... 
          'Position',[0.1 0.32 0.27 0.1],... 
          'backgroundcolor',[0.9 0.9 0.9] ,... 
          'foregroundcolor','black',... 
          'fontweight','bold',... 
          'fontsize',10,... 
          'string','f',... 
          'Parent',Parameters);  
 % edit for f      
 uicontrol('Style','edit',...  
           'Units','normalized',... 
           'Position',[0.5 0.32 0.27 0.1],... 
           'backgroundcolor',[0.9 0.9 0.9],... 
           'foregroundcolor','black',... 
           'fontweight','bold',... 
           'fontsize',10,... 
           'String',f,... 
           'Parent',Parameters,... 
'Callback',['f=str2num(get(gco,"String")),' ... 
'myInterface(avin,d,A,R1,R2,Vps1,Vps2,f,N)']); 
 
% text button for A            
uicontrol('Style','text',... 
          'Units','normalized',... 
          'Position',[0.1 0.21 0.27 0.1],... 
          'backgroundcolor',[0.9 0.9 0.9] ,... 
          'foregroundcolor','black',... 
          'fontweight','bold',... 
          'fontsize',10,... 
          'String','A',... 
          'Parent',Parameters);  
 % edit for A      
uicontrol('Style','edit',... 
          'Units','normalized',... 
          'Position',[0.5 0.21 0.27 0.1],... 
          'backgroundcolor',[0.9 0.9 0.9],... 
          'foregroundcolor','black',... 
          'fontweight','bold',... 
          'fontsize',10,... 
          'String',A,... 
          'Parent',Parameters,... 
'Callback',['A=str2num(get(gco, "String")),' ... 
'myInterface(avin,d,A,R1,R2,Vps1,Vps2,f,N)']); 
 
% text button for N 
uicontrol('Style','text',... 
          'Units','normalized',... 
          'Position',[0.1 0.1 0.27 0.1],... 
          'backgroundcolor',[0.9 0.9 0.9] ,... 
          'foregroundcolor','black',... 
          'fontweight','bold',... 
          'fontsize',10,... 
          'String','N',... 
          'Parent',Parameters); 
% edit for N       
uicontrol('Style','edit',... 
          'Units','normalized',... 
          'Position',[0.5 0.1 0.27 0.1],... 
          'backgroundcolor',[0.9 0.9 0.9],... 
          'foregroundcolor','black',... 
          'fontweight','bold',... 
          'fontsize',10,... 
          'String',N,... 
          'Parent',Parameters,... 
'Callback',['N=str2num(get(gco, "String")),' ... 
'myInterface(avin,d,A,R1,R2,Vps1,Vps2,f,N)']); 
 
% calculates the gain for each amplifier 
if avin==0  
   %voltage gain for noninverting amp 
    Av=1+R2./R1;      
else  
%voltage gain for inverting amp 
    Av=-(R2./R1);          
end 
 
%period 
T=1/f;           
%time range 
t=0:T/1000:N*T;  
 
% Calculates the input and output voltages 
% for each type of amplifier 
if d==1   % d==1 sine wave 
       Vi=A*sin(2*pi*f*t); 
       Vo=Av*A*sin(2*pi*f*t); 
    else                     % d=2 triangular wave 
        Vi=(2.*A./pi).*asin(sin(2*pi*f*t)); 
        Vo=Av*(2.*A/pi).*asin(sin(2*pi*f*t)); 
end 
%limitations for the current 
k=max(size(t)); 
for i=1:k 
    if(Vo(i)>Vps1)    % Vps1 = +Vps 
        Vo(i)=Vps1; 
    end 
    if(Vo(i)<Vps2)    % Vps2 = -Vps 
        Vo(i)=Vps2; 
    end 
end 
clear k; 
% plot for Vi= input voltage 
subplot('position',[0.55 0.72 0.4 0.25]); 
plot(t,Vi,'-.k'); 
grid on; 
title('Input Voltage'); 
xlabel('time [s]'); 
ylabel('Amplitude [V]'); 
legend('Vi'); 
% plot for Vo= output voltage 
subplot('position',[0.55 0.38 0.4 0.25]); 
plot(t,Vo,'--b'); 
grid on; 
title('Output Voltage'); 
xlabel('time [s]'); 
ylabel('Amplitude [V]'); 
legend('Vo'); 
% plot for x=Vi, y=Vo  
subplot('position',[0.55 0.05 0.4 0.25]); 
plot(Vi,Vo,'-r'); 
grid on; 
title('VTC'); 
xlabel('Input Voltage [V]'); 
ylabel('Output Voltage [V]'); 
legend('Vo/Vi'); 
% end of the function file myInterface.m 
end 