%Simple Voltage Divider Calculator

close all; 
clc; 
Fig=figure('Name','Voltage Divider',...  
  'Units','normalized',...      
  'Position',[.3 .3 .4 .3],... 
  'NumberTitle','off');        
% Display the Image                  
imageV = 'voltage_divider.png'; 
 
% Read the image using imread 
img = imread(imageV); 
 
% Create axes in specified position within the figure  
ax = axes('Position', [0.08 0.2 0.42 0.58]); 
% Displays the image within specified axes 
% axes are PARENT for the image 
imshow(img, 'Parent', ax); 
% Adds a Close button  
uicontrol(Fig,'Style','pushbutton',...  
      'Units','normalized',...  
     'Position',[0.87 0.02 0.12 0.1],...  
     'String','CLOSE',...  
     'Callback','close'); 
 
% Add static text above the image 
uicontrol('Style', 'text', ... 
          'Units', 'normalized', ... 
          'Position', [0.18 0.75 0.2 0.1], ...  
          'backgroundcolor','w',...  
          'foregroundcolor','red',...  
          'String', 'Voltage Divider', ... 
          'FontWeight','bold','FontSize', 12);  
% Add static text for Vin 
uicontrol('Style', 'text', ... 
          'Units', 'normalized', ... 
          'Position', [0.5 0.65 0.2 0.1], ...  
          'String', 'Vin (V):', ... 
          'FontWeight','bold','FontSize', 10); 
 
% Add static text indicating  
% the formula calculus for Vout 
txt=uicontrol('Style','text',...  
 'Units','normalized',...  
'Position',[0.56 0.85 0.28 0.06],...  
'backgroundcolor','w',...  
'foregroundcolor','blue',...  
'String','Vout = (R2 / (R1 + R2)) * Vin',... 
'FontWeight','bold','FontSize', 12); 
 
% Add edit text box for the input voltage input 
editVin = uicontrol('Style', 'edit', ... 
                   'Units', 'normalized', ... 
                   'Position', [0.68 0.68 0.06 0.07], ... 
                   'BackgroundColor', 'white', ... 
                   'FontSize', 9, ... 
 'Callback','Vin=str2double(get(editVin,"String"));'); 
 
% Add static text for Resistance 1 
uicontrol('Style', 'text', ... 
          'Units', 'normalized', ... 
          'Position', [0.5 0.55 0.2 0.1], ...  
          'String', 'R1 (kΩ):', ... 
          'FontWeight','bold','FontSize', 10); 
 
% Add editbox for Resistance 1 input 
editR1 = uicontrol('Style', 'edit', ... 
                     'Units', 'normalized', ... 
                     'Position', [0.68 0.58 0.06 0.07], ... 
                     'BackgroundColor', 'white', ... 
                   'FontSize', 9, ... 
'Callback','R1=str2double(get(editR1,"String"));');  
 
% Add static text for Resistance 2 
uicontrol('Style', 'text', ... 
          'Units', 'normalized', ... 
          'Position', [0.5 0.45 0.2 0.1], ...  
          'String', 'R2 (kΩ):', ... 
          'FontWeight','bold','FontSize', 10); 
 
% Add edit text box for Resistance 2 input 
editR2 = uicontrol('Style', 'edit', ... 
                     'Units', 'normalized', ... 
                     'Position', [0.68 0.48 0.06 0.07], ... 
                     'BackgroundColor', 'white', ... 
                     'FontSize', 9, ... 
'Callback','R2 = str2double(get(editR2, "String"));');   
% Add static text for Vout  
voutDisplay = uicontrol('Style', 'text', ... 
          'Units', 'normalized', ... 
          'Position', [0.65 0.2 0.2 0.1], ...  
          'String', 'Vout:', ... 
          'FontWeight','bold','FontSize', 10); 
 
% Add a pushbutton for calculating the 
% R2 voltage drop 
uicontrol('Style','pushbutton', ...
          'Units','normalized', ...
          'Position',[0.55 0.22 0.13 0.1], ...
          'String','Calculate', ...
          'FontSize',10, ...
          'Callback','Vout=(R2/(R1+R2))*Vin; set(voutDisplay,''String'', sprintf(''Vout: %.2f V'', Vout));');