%Consider a sine function that needs to be displayed into a MatLab figure, while allowing the 
%modification of the signal's amplitude. The initial values are amplitude A=1, frequency=50Hz, the time 
%defined from 0 to 2T with a step of T/100. The function y is defined as y=A*sin(2π*f*t). 

close all; 
A=1;   
f=50; 
Fig=figure('Name','Sine Function',... 
'Units','normalized',...
'Position',[0.3 0.3 0.6 0.6],... 
'Color',[0.5 0.5 0.9],... 
'NumberTitle','off'); 
uicontrol('Style','pushbutton',...  
'Units','normalized',... 
'Position',[0.91 0.02 0.1 0.04],... 
'String','CLOSE',...
'Callback','close');
sinus(A,f);