function sinus(A,f) 
uicontrol('Style','text', ... 
'Units','normalized', ... 
'Position',[0.91 0.95 0.1 0.04], ... 
'String','A - Sinus Amplitude'); 
uicontrol('Style','edit',... 
'Units','normalized',... 
'Position',[0.91 0.9 0.1 0.04],... 
'String',A,... 
'Callback',['A=str2num(get(gco,''String''));sinus(A,f);']); 
uicontrol('Style','text', ... 
'Units','normalized', ... 
'Position',[0.91 0.85 0.1 0.04], ... 
'String','f - Frequency'); 
uicontrol('Style','edit',... 
'Units','normalized',... 
'Position',[0.91 0.8 0.1 0.04],... 
'String',f,... 
'Callback','f=str2num(get(gco,''string''));sinus(A,f);'); 
T=1/f; 
t=0:T/100:2*T; 
y=A*sin(2*pi*f*t); 
plot(t,y); 
grid on; 
title('Sinus Plot') 
xlabel(' Frequency f [Hz]') 
ylabel(' Amplitude A ') 
end 