%a simple instantiation in Matlab code
clear all;  
close all;  
Fig=figure('Name','New MatLab Figure',...  
'Units','normalized',... 
'Position',[.1 .1 .5 .5],...  
'NumberTitle','off',... 
'Color',[0 0.5 0.5] );  