%Simple UI elements

% Creating a pushbutton: 
GO_p=uicontrol('Style','pushbutton',... %graphics object type 
'Units','normalized',...    
'Position',[0.05 0.15 0.15 0.1],... %position in the figure window 
'String','CLOSE',... %text on the button 
'Callback','close'); %function called when the button is pressed

GO_t=uicontrol('Style','text',... %graphics object type 
'Units','normalized',...  
'Position',[0.3 0.85 0.16 0.05],... %position inside the figure window 
'backgroundcolor','w',...  %of the button 
'foregroundcolor','blue',... %of the text 
'String','LOW PASS FILTER');   % label on the button 
uicontrol('Style','text',... 
'Units','normalized',... 
'Position',[0.775 0.05 0.2 0.1],... 
'foregroundcolor','r',... 
'String','A Button to PUSH'); 
% Creating an edit object: 
GO_e=uicontrol('Style','edit',...  
'Units','normalized',... 
'Position',[0.6 0.85 0.16 0.05],... 
'foregroundcolor','r',... 
'String',20,...  %initial value-string, that the user can change 
'Callback','');

% Creating a popupmenu object:  
GO_ppm=uicontrol('Style','PopupMenu',... 
'Units','normalized',... 
'Position',[0.8 0.85 0.06 0.05],... 
'String','LPF|BPF|HPF',... 
'Callback','');

% Creating a checkbox. They behave as an on-off switch 
GO_cbx1=uicontrol('Style','Checkbox',...  
'Units','normalized',...  
'String','CheckBox A',...  
'BackgroundColor','y',...  
'Position', [0.07 .7 .1 .1],...  
'Callback','') 
GO_cbx2=uicontrol('Style','Checkbox',...  
'Units','normalized',...  
'String','CheckBox B',...  
'BackgroundColor','y',...  
'Position', [0.07 .6 .1 .1],...  
'Callback','')

% Creating a radiobutton object 
GO_rb1=uicontrol('Style','radiobutton',...  
'Units','normalized',...  
'Position',[0.85 0.7 .1 .1],...  
'String',' RB1',...  
'Callback','') ; 
GO_rb2=uicontrol('Style','radiobutton',...  
'Units','normalized',...  
'Position',[0.85 0.6 .1 .1],...  
'String',' RB2',...  
'Callback','') ; 

% Creating a slider object 
GO_s=uicontrol('Style','slide',...  %the slider 
'Units','normalized',...  
'Position',[0.4 0.6 .1 .05],...  %slider position 
'Min',-150,'Max',150,'Value',1,... %min and max values indicated  
'Callback','') ; 
uicontrol('Style','text',...    %defining the minimal value 
'Units','normalized',...  
'Position',[0.37 0.6 0.03 0.05],... %!Min value position on the slider 
'backgroundcolor','y',...  
'foregroundcolor','black',...  
'String',num2str(get(GO_s,'Min'))); 
uicontrol('Style','text',...    %defining the maximal value 
'Units','normalized',...  
'Position',[0.5 0.6 0.03 0.05],... %!Max value position on the slider 
'backgroundcolor','y',...  
'foregroundcolor','black',...  
'String',num2str(get(GO_s,'Max')));